### ISSUE TITLE
Bad gateway when trying to get factors of Virahanka-Fibonacci numbers

### ISSUE THREAD

**Issue by gwhitney** [numberscope/backscope#143]
Currently attempting to fetch https://numberscope.colorado.edu/api/get_oeis_factors/A000045/128 returns an error 502 "Bad Gateway". Note that the same requests for A000001 (number of groups) and A000040 (primes) return fine.

This is a blocker for https://github.com/orgs/numberscope/discussions/7

**Comment by gwhitney** [comment]
Hmm, nothing at all about A000045 in the api.log...

**Comment by gwhitney** [comment]
However, in /var/log/nginx/error.log there were numerous entries of the form
```
2024/07/20 14:01:12 [error] 1739#1739: *408 upstream prematurely closed connection while reading response 
header from upstream, client: 47.155.111.72, server: numberscope.colorado.edu, request: "GET /api/get_oeis
_factors/A000045/128 HTTP/1.1", upstream: "http://unix:/home/scope/repos/backscope/backscope.sock:/api/get
_oeis_factors/A000045/128", host: "numberscope.colorado.edu"
```
so that's probably some kind of clue.

**Comment by gwhitney** [comment]
And indeed, each attempt to load the offending URL from numberscope.colorado.edu results in another copy of such an error.log entry. And judging from https://stackoverflow.com/questions/36488688/nginx-upstream-prematurely-closed-connection-while-reading-response-header-from, the message seems to mean that the python process to produce the result is either crashing or returning nothing. So why isn't there anything in the backscope logs?

**Comment by gwhitney** [comment]
Oh, the journalctl command in the administration guide was wrong. It should be `sudo journalctl -u numberscope` (I will submit a PR to fix). And that produces lots of messages like:
```
[2024-07-20 14:15:43 -0600] [6776] [INFO] Worker exiting (pid: 67>
 Traceback (most recent call last):
   File "/home/scope/repos/backscope/.venv/bin/gunicorn", line 8, >
     sys.exit(run())
              ^^^^^
   File "/home/scope/repos/backscope/.venv/lib/python3.11/site-pac>
     WSGIApplication("%(prog)s [OPTIONS] [APP_MODULE]").run()
   File "/home/scope/repos/backscope/.venv/lib/python3.11/site-pac>
     super().run()
   File "/home/scope/repos/backscope/.venv/lib/python3.11/site-pac>
     Arbiter(self).run()
   File "/home/scope/repos/backscope/.venv/lib/python3.11/site-pac>
     self.manage_workers()
   File "/home/scope/repos/backscope/.venv/lib/python3.11/site-pac>
     self.spawn_workers()
   File "/home/scope/repos/backscope/.venv/lib/python3.11/site-pac>
     self.spawn_worker()
   File "/home/scope/repos/backscope/.venv/lib/python3.11/site-pac>
     worker.init_process()
   File "/home/scope/repos/backscope/.venv/lib/python3.11/site-pac>
     self.run()
   File "/home/scope/repos/backscope/.venv/lib/python3.11/site-pac>
     self.run_for_one(timeout)
   File "/home/scope/repos/backscope/.venv/lib/python3.11/site-pac>
    self.accept(listener)
   File "/home/scope/repos/backscope/.venv/lib/python3.11/site-pac>
     self.handle(listener, client, addr)
   File "/home/scope/repos/backscope/.venv/lib/python3.11/site-pac>
     self.handle_request(listener, req, client, addr)
   File "/home/scope/repos/backscope/.venv/lib/python3.11/site-pac>
     respiter = self.wsgi(environ, resp.start_response)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   File "/home/scope/repos/backscope/.venv/lib/python3.11/site-pac>
     return self.wsgi_app(environ, start_response)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   File "/home/scope/repos/backscope/.venv/lib/python3.11/site-pac>
     response = self.full_dispatch_request()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   File "/home/scope/repos/backscope/.venv/lib/python3.11/site-pac>
     rv = self.dispatch_request()
          ^^^^^^^^^^^^^^^^^^^^^^^
   File "/home/scope/repos/backscope/.venv/lib/python3.11/site-pac>
     return self.ensure_sync(self.view_functions[rule.endpoint])(*>
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^>
   File "/home/scope/repos/backscope/flaskr/nscope/views.py", line>
     seq = fetch_factors(valid_oeis_id, wants)
   File "/home/scope/repos/backscope/flaskr/nscope/views.py", line>
   fac = gen_to_python(pari(val).factor())
                         ^^^^^^^^^^^^^^^^^^
   File "cypari2/gen.pyx", line 4363, in cypari2.gen.Gen.factor
cysignals.signals.SignalError: Illegal instruction
```
so this seems to be cypari acting up again... I will see if I can reproduce running locally.

**Comment by gwhitney** [comment]
Hmm, running on my machine, get_factors for A000045 had no problems, although starting at VF(290), it started reporting "no_fac" rather than a factorization, presumably because the numbers got so large.
